___
<a href = 'https://www.tradingvalley.com/en/'> 
    <img src = 'fig/TV_logo.jpg' width = '50%'/>
    </a>
<h6 style = "text-align:right"> Python and Quantitative Trading @ NTHU 107 </h6>

___

<h1 style = "text-align:center"> Python Introduction </h1>

## 1-1. Data types（Data Structures）

<img src = 'fig/data_structure.png' width = '70%'/>

#### 查看變數資料結構：
```python
type()
```
#### 在 IPython 上顯示變數
```python
from IPython.display import display
display()
```
#### 在 Python 中印出變數、文字
```python
print('abc')
print(var)
```

In [1]:
from IPython.display import display

### integer

In [2]:
a_integer = 1
print("type of a_integer：%s." %type(a_integer))

display(a_integer)

type of a_integer：<class 'int'>.


1

### float

In [3]:
a_float = 1.
print("type of a_float：%s." %type(a_float))

display(a_float)

type of a_float：<class 'float'>.


1.0

In [4]:
a_float = 3.8
print("type of a_float：%s." %type(a_float))

display(a_float)

type of a_float：<class 'float'>.


3.8

### string

字串可以使用單引號（`'abc'`）或雙引號（`"abc"`）<br> <br>
當使用三個單/雙引號時（`'''abc'''`或是`"""abc"""`），則會代表輸入的字面格式。

In [5]:
a_character = 'a'
print("type of a_character：%s." %type(a_character))

display(a_character)

type of a_character：<class 'str'>.


'a'

In [6]:
a_string = 'apple'
print("type of a_string：%s." %type(a_string))

display(a_string)

type of a_string：<class 'str'>.


'apple'

In [7]:
a_string = 'TV_0914'
print("type of a_string：%s." %type(a_string))

display(a_string)

type of a_string：<class 'str'>.


'TV_0914'

In [8]:
a_string = '立鼎資訊'
print("type of a_string：%s." %type(a_string))

display(a_string)

type of a_string：<class 'str'>.


'立鼎資訊'

In [9]:
a_string = '立鼎資訊，TradingValley'
print("type of a_string：%s." %type(a_string))

display(a_string)

type of a_string：<class 'str'>.


'立鼎資訊，TradingValley'

In [10]:
a_paragraph = """立鼎資訊就是
TradingValley"""
print("type of a_paragraph：%s." %type(a_paragraph))

display(a_paragraph)

type of a_paragraph：<class 'str'>.


'立鼎資訊就是\nTradingValley'

In [11]:
a_paragraph = '''TradingValley就是
立鼎資訊'''
print("type of a_paragraph：%s." %type(a_paragraph))

display(a_paragraph)

type of a_paragraph：<class 'str'>.


'TradingValley就是\n立鼎資訊'

#### 字串特殊顯示方式

從上面的例子中可以知道，`'\n'`代表的是換行，在字串顯示中，還有一些此類的顯示方式：

- `\n`： 換行
- `\t`： 等同於在文句中輸入 tab 鍵<br>

- `\r`： 重新輸入（前面的文字不會被刪除，但是會從頭開始印接下來的句子）<br>

In [12]:
print('This is Jasper.\nProgramming\tis\tFUN!!!')

This is Jasper.
Programming	is	FUN!!!


In [13]:
print('Programming is FUN!!!')
print('Programming is FUN\r NOT!!!')

Programming is FUN!!!
 NOT!!!


#### 輸出多個變數在句子中

若要在一個句子中插入變數的文字時，可以用 `%s`、`%d`、`%f`、`%e` 等等表示。

- %c：字元
- %s：字串
- %d：整數
- %f：浮點數
- %e：科學記號

In [14]:
var = 'a'

print('%c' %var)

a


In [15]:
var = 'abc'

print('%c' %var)

TypeError: %c requires int or char

In [16]:
var = 'abc'

print('%s' %var)

abc


In [17]:
var = 'a'

print('%s' %var)

a


In [18]:
var = 1

print('%d' %var)

1


In [19]:
var = 1

print('%f' %var)

1.000000


In [20]:
var = 1.5

print('%f' %var)

1.500000


In [21]:
var = 1.5

print('%d' %var)

1


In [22]:
var = 0.000001

print('%e' %var)

1.000000e-06


> 所以，在某些時候`%`百分比符號就沒辦法直接在句子中顯示了，需要使用`%%`！

In [23]:
print('100%score')

100%score


In [24]:
name = 'Jasper'

print('%s got 100%score' %name)

TypeError: not enough arguments for format string

In [25]:
print('%s got 100%%score' %name)

Jasper got 100%score


### boolean

boolean 是布林值，也就是邏輯的資料結構（True 或 False）

In [26]:
a_boolean = True
print("type of a_boolean：%s." %type(a_boolean))

display(a_boolean)

type of a_boolean：<class 'bool'>.


True

In [27]:
a_boolean = False
print("type of a_boolean：%s." %type(a_boolean))

display(a_boolean)

type of a_boolean：<class 'bool'>.


False

### lists

#### 以中括號`[ ]`表示

list 是 python 中基本的資料結構，主要是一個`儲存` `不同元素`的一個資料結構，<br>
並能夠對這些元素進行搜尋、新增、刪減、組合等等。

In [28]:
a_list = [1, 'TradingValey', '立鼎好棒棒', True]
print("type of a_list：%s." %type(a_list))

display(a_list)

type of a_list：<class 'list'>.


[1, 'TradingValey', '立鼎好棒棒', True]

> Python 選取元素時，由 `0` 開始數！

In [29]:
a_list = [1, 'TradingValey', '立鼎好棒棒', True]

display(a_list[1])

'TradingValey'

In [30]:
a_list = [1, 'TradingValey', '立鼎好棒棒', True]

display(a_list[0])

1

### tuples

#### 以小括號`( )`表示

tuple 與 list 大同小異，只是 tuple 中的元素`不能夠被修改`，<br>
但仍可以被搜尋、新增、組合。

In [31]:
a_tuple = (1, 'TradingValey', '立鼎好棒棒', True)
print("type of a_tuple：%s." %type(a_tuple))

display(a_tuple)

type of a_tuple：<class 'tuple'>.


(1, 'TradingValey', '立鼎好棒棒', True)

> list 和 tuple 最大的不同是：
> `list` 中的元素都可以被修改，但是 `tuple` 中的不行。

In [32]:
a_list[0] = 2

display(a_list)

[2, 'TradingValey', '立鼎好棒棒', True]

In [33]:
a_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

> 另外，由於 list 和 tuple 中可以包涵不同的資料結構，因此`沒辦法直接進行運算`。

In [34]:
a = [1, 2, 3]
b = [4, 5, 6]

a - b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [35]:
a = (1, 2, 3)
b = (4, 5, 6)

a - b

TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

> 若希望進行數學運算，需要先將變數的資料結構改為 `array` 或 `matrix`。（將在下面做介紹）

> 另外， tuple 資料結構中，至少需要有兩個元素

In [36]:
not_a_tuple = (1)
print("type of not_a_tuple：%s." %type(not_a_tuple))

display(not_a_tuple)

type of not_a_tuple：<class 'int'>.


1

In [37]:
a_tuple = (1, 2)
print("type of a_tuple：%s." %type(a_tuple))

display(a_tuple)

type of a_tuple：<class 'tuple'>.


(1, 2)

In [38]:
not_a_tuple = ('a')
print("type of not_a_tuple：%s." %type(not_a_tuple))

display(not_a_tuple)

type of not_a_tuple：<class 'str'>.


'a'

In [39]:
a_tuple = ('a', 'b')
print("type of a_tuple：%s." %type(a_tuple))

display(a_tuple)

type of a_tuple：<class 'tuple'>.


('a', 'b')

### dictionary

<img src = 'fig/dictionary.jpg' width = '20%'/>

dictionary 包含了兩個部分
1. `key` （以字典而言就是「字母」）
2. `value`（以字典而言就是「單字」）

表示方式為：
```python
{key: value}
```
可以有多個（key, value），各自中間以逗號 `,` 分割。
```python
{
    key1: value1,
    key2: value2
}
```

In [40]:
a_dict = {
    'a': ['apple', 'air'],
    'b': ['book', 'ball'],
    'c': ['cook']
}
print('type of a_dict：%s.' %type(a_dict))

display(a_dict)

type of a_dict：<class 'dict'>.


{'a': ['apple', 'air'], 'b': ['book', 'ball'], 'c': ['cook']}

In [41]:
a_dict.keys()

dict_keys(['a', 'b', 'c'])

In [42]:
a_dict.values()

dict_values([['apple', 'air'], ['book', 'ball'], ['cook']])

In [43]:
a_dict['a']

['apple', 'air']

### dataframe

dataframe 是一個很特殊的資料結構，與表格相近，需要事先 import `pandas` 這個模組才能使用。
``` python
import pandas
```
註：模組相關內容在往後會介紹。

dataframe 這個資料結構好處是可以幫助我們很輕鬆地進行`資料的處理`（也是於往後的模組介紹中舉例）。

In [44]:
import pandas

In [45]:
a_df = pandas.DataFrame([1, 2, 3])
print('type of a_df：%s.' %type(a_df))

display(a_df)

type of a_df：<class 'pandas.core.frame.DataFrame'>.


0
0  1
1  2
2  3

In [46]:
a_df = pandas.DataFrame([[1, 2, 3], [4, 5, 6]])
print('type of a_df：%s.' %type(a_df))

display(a_df)

type of a_df：<class 'pandas.core.frame.DataFrame'>.


0  1  2
0  1  2  3
1  4  5  6

> 我們也可以自行設定 dataframe 的欄位名稱（`columns`）及列位名稱（`index`）

In [47]:
a_df = pandas.DataFrame([[1, 2, 3], [4, 5, 6]],
                                     columns = ['欄1', '欄2', '欄3'],
                                     index = ['列1', '列2'])
print('type of a_df：%s.' %type(a_df))

display(a_df)

type of a_df：<class 'pandas.core.frame.DataFrame'>.


欄1  欄2  欄3
列1   1   2   3
列2   4   5   6

> 要選取 dataframe 中的元素時，`先選擇欄，再選擇列`。

In [48]:
a_df['欄1']['列2']

4

### datetime

datetime 也是需要 import 一個模組（`datetime`）才能使用的資料結構。
``` python
import datetime
```
datetime 顧名思義就是與`時間、日期`相關的資料結構，方便我們進行時間、日期上的計算。

In [49]:
import datetime

In [50]:
a_datetime = datetime.datetime(2018, 5, 4)
print('type of a_datetime：%s.' %type(a_datetime))

display(a_datetime)

type of a_datetime：<class 'datetime.datetime'>.


datetime.datetime(2018, 5, 4, 0, 0)

### array and matrix

array 與 matrix 則是需要 import `numpy` 模組。
``` python
import numpy
```
由於 list 和 tuple 沒辦法直接進行數值上的運算（因為可以包含不同資料結構的元素），<br>
若要進行`數學上的運算`，尤其是矩陣運算，需要使用 array 或 matrix 的資料結構。<br><br>
註：強大的 dataframe 也支援矩陣的運算

In [51]:
import numpy

In [52]:
a_array = numpy.array([1, 2, 3])
print('type of a_array：%s.' %type(a_array))

display(a_array)

type of a_array：<class 'numpy.ndarray'>.


array([1, 2, 3])

> 以 array 的資料結構，就可以直接做數值的運算了！

In [53]:
a = numpy.array([1, 2, 3])
b = numpy.array([4, 5, 6])

a - b

array([-3, -3, -3])

In [54]:
a_matrix = numpy.matrix([1, 2, 3])
print('type of a_matrix：%s.' %type(a_matrix))

display(a_matrix)

type of a_matrix：<class 'numpy.matrixlib.defmatrix.matrix'>.


matrix([[1, 2, 3]])

In [55]:
a_matrix = numpy.matrix([[1, 2, 3], [4, 5, 6]])
print('type of a_matrix：%s.' %type(a_matrix))

display(a_matrix)

type of a_matrix：<class 'numpy.matrixlib.defmatrix.matrix'>.


matrix([[1, 2, 3],
        [4, 5, 6]])

> 以下是一個簡單的矩陣運算範例（transpose，轉置矩陣）

In [56]:
a_matrix.T

matrix([[1, 4],
        [2, 5],
        [3, 6]])

### Let you try try~

Jupyter Notebook 的另一好處，能察看每個變數型態可以使用的方法。
（在一個變數後`輸入「一點」再按 tab 鍵`）

由於 dataframe 是一個方便進行資料分析、計算、應用的資料結構，
所以以下以 dataframe 為例子：

In [57]:
import pandas

my_data = pandas.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
                                           columns = ['A', 'B', 'C'],
                                           index = ['a', 'b', 'c', 'd'])

display(my_data)

A   B   C
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

<img src = 'fig/variable_methods.png' width = '60%'/>

In [58]:
my_data.min()

A    1
B    2
C    3
dtype: int64

In [59]:
my_list = ['c', 'a', 'd', 'b']

display(my_list)

['c', 'a', 'd', 'b']

In [60]:
my_list.sort()
display(my_list)

['a', 'b', 'c', 'd']

- 更多詳細的 dataframe 使用方法將在之後做介紹，不過大家也可以自行先摸索看看！

[_]( http://localhost:8888/notebooks/Courses/NTHU/0_Overview.ipynb) <br>
[_]( http://localhost:8888/notebooks/Courses/NTHU/1_2_Operators.ipynb)